### ISSUE TITLE
API Gateway crashing

### ISSUE THREAD

**Issue by juhideshkar30** [airavata-courses/Noodle#70]
Kubernetes: The connection to the server was refused.
API gateway seems to be crashing.

**Comment by nayeembaig** [comment]
This was because of not configuring API gateway with Kafka. This was rectified.

https://github.com/airavata-courses/Noodle/commit/78016ad42541c5e375644a4232ac990b50eddd82

https://github.com/airavata-courses/Noodle/commit/379a1f95af9671e22df1eb7ccd267385ad3b9a60
