### ISSUE TITLE
No response for register and login functionality

### ISSUE THREAD

**Issue by shindedarshan** [airavata-courses/Noodle#76]
I tried to register a new user on the given application URL. I got no indication of whether it succeeded or failed. Then I tried login, again nothing happens.

**Comment by rut999** [comment]
Thanks for pointing it out.
Password should be of 6 characters .
Once you have registered you will get a success prompt .Then you can try logging in.
We should have mentioned it in the wiki.

**Comment by shindedarshan** [comment]
There should be a failure message similar to success in case of an unsuccessful register and log in.
