### ISSUE TITLE
No information in wiki about how to use application after login

### ISSUE THREAD

**Issue by shindedarshan** [airavata-courses/Noodle#79]
No information about how to check weather data. There is a dropdown but as an end-user, I am not getting this what it is doing.

**Comment by naga-anjaneyulu** [comment]
Once you login , you have to select any one of the station and click run command .
Once you click the run command, it navigates you to the next page letting you know the job status .
You can check the current status of the job by clicking refetch button  and notice that the the status of the job moves from  data retrieval to processing to model executed .
you might log out any time after clicking the run command and come back later and check previous session data by clicking on session button on the home page .Once you click session button on the home, you would be able to check the status of the previous session's job status.
